# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 屠城
subtitle: 屠夫9441的博客
description: 屠城 | 屠夫9441 | 博客 | 独立博客 | hexo | typecho | wordpress | 心情 | 随笔
author: 屠夫9441
email: tufu9441@gmail.com
language: zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://haomwei.com
root: /
permalink: :category/:title.html
tag_dir: tags
about_dir: about
history_dir: history
archive_dir: archives
guestbook_dir: guestbook
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: coney
stylus:
  compress: true
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
     github: https://github.com/tufu9441/tufu9441.github.io.git,master
     gitcafe: https://gitcafe.com/tufu9441/tufu9441.git,gitcafe-pages

plugins:
  - hexo-generator-sitemap
  - hexo-generator-feed
  - hexo-generator-robotstxt

baidusitemap:
    path: baidusitemap.xml

backup:
    type: git
    repository:
       github: git@github.com:tufu9441/hexo.git,master
